list: $/impulsetechnologies/loanmanagement/models/loanpurpose/columns.yaml
modelClass: ImpulseTechnologies\LoanManagement\Models\LoanPurpose
title: LoanPurposes
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'impulsetechnologies/loanmanagement/loanpurposes/update/:id'
